[opam]
compiler = "5.4.0"

[[opam.repositories]]
name = "default"
path = "/workspace/opam-repository"

[[opam.repositories]]
name = "aoah"
path = "/workspace/opam/aoah-opam-repo"

[[opam.vendored]]
name = "bigstringaf"
url = "https://github.com/inhabitedtype/bigstringaf.git"

[[opam.vendored]]
name = "csexp"
url = "https://github.com/ocaml-dune/csexp.git"

[[opam.vendored]]
name = "cstruct"
url = "https://github.com/mirage/ocaml-cstruct.git"

[[opam.vendored]]
name = "domain-local-await"
url = "https://github.com/ocaml-multicore/domain-local-await.git"

[[opam.vendored]]
name = "dune"
url = "https://github.com/ocaml/dune.git"

[[opam.vendored]]
name = "eio"
url = "https://github.com/ocaml-multicore/eio.git"

[[opam.vendored]]
name = "fmt"
url = "https://erratique.ch/repos/fmt.git"

[[opam.vendored]]
name = "hmap"
url = "http://erratique.ch/repos/hmap.git"

[[opam.vendored]]
name = "iomux"
url = "https://github.com/ocaml-multicore/ocaml-iomux.git"

[[opam.vendored]]
name = "lwt-dllist"
url = "https://github.com/mirage/lwt-dllist.git"

[[opam.vendored]]
name = "mtime"
url = "https://erratique.ch/repos/mtime.git"

[[opam.vendored]]
name = "ocamlbuild"
url = "https://github.com/ocaml/ocamlbuild.git"

[[opam.vendored]]
name = "ocamlfind"
url = "https://github.com/ocaml/ocamlfind.git"

[[opam.vendored]]
name = "optint"
url = "https://github.com/mirage/optint.git"

[[opam.vendored]]
name = "psq"
url = "https://github.com/pqwy/psq.git"

[[opam.vendored]]
name = "seq"
url = "https://github.com/ocaml/ocaml.git"

[[opam.vendored]]
name = "thread-table"
url = "https://github.com/ocaml-multicore/thread-table.git"

[[opam.vendored]]
name = "topkg"
url = "https://erratique.ch/repos/topkg.git"

[[opam.vendored]]
name = "uring"
url = "https://github.com/ocaml-multicore/ocaml-uring.git"

[[opam.vendored]]
name = "logs"
url = "https://erratique.ch/repos/logs.git"

[[opam.vendored]]
name = "jsont"
url = "https://erratique.ch/repos/jsont.git"

[[opam.vendored]]
name = "ptime"
url = "https://erratique.ch/repos/ptime.git"

[[opam.vendored]]
name = "tomlt"
url = "https://tangled.org/@anil.recoil.org/ocaml-tomlt.git"

[[opam.vendored]]
name = "cmdliner"
url = "https://erratique.ch/repos/cmdliner.git"

[[opam.vendored]]
name = "0install-solver"
url = "https://github.com/0install/0install.git"

[[opam.vendored]]
name = "jsonm"
url = "https://erratique.ch/repos/jsonm.git"

[[opam.vendored]]
name = "ocamlgraph"
url = "https://github.com/backtracking/ocamlgraph.git"

[[opam.vendored]]
name = "opam-0install"
url = "https://github.com/ocaml-opam/opam-0install-solver.git"

[[opam.vendored]]
name = "opam-core"
url = "https://github.com/ocaml/opam.git"

[[opam.vendored]]
name = "opam-file-format"
url = "https://github.com/ocaml/opam-file-format"

[[opam.vendored]]
name = "patch"
url = "https://github.com/hannesm/patch.git"

[[opam.vendored]]
name = "re"
url = "https://github.com/ocaml/ocaml-re.git"

[[opam.vendored]]
name = "sha"
url = "https://github.com/djs55/ocaml-sha.git"

[[opam.vendored]]
name = "spdx_licenses"
url = "https://github.com/kit-ty-kate/spdx_licenses.git"

[[opam.vendored]]
name = "stdlib-shims"
url = "https://github.com/ocaml/stdlib-shims.git"

[[opam.vendored]]
name = "swhid_core"
url = "https://github.com/ocamlpro/swhid_core.git"

[[opam.vendored]]
name = "uutf"
url = "https://erratique.ch/repos/uutf.git"

[[opam.vendored]]
name = "claude"
url = "https://tangled.org/@anil.recoil.org/ocaml-claudeio.git"

[[opam.vendored]]
name = "digestif"
url = "https://github.com/mirage/digestif.git"

[[opam.vendored]]
name = "eqaf"
url = "https://github.com/mirage/eqaf.git"

[[opam.vendored]]
name = "base64"
url = "https://github.com/mirage/ocaml-base64.git"

[[opam.vendored]]
name = "astring"
url = "http://erratique.ch/repos/astring.git"

[[opam.vendored]]
name = "fpath"
url = "https://erratique.ch/repos/fpath.git"

[[opam.vendored]]
name = "bytesrw"
url = "https://erratique.ch/repos/bytesrw.git"

[[opam.vendored]]
name = "menhir"
url = "https://github.com/LexiFi/menhir.git"
